### ISSUE TITLE
Issue with Gates test 

### ISSUE THREAD

**Issue by haswal** [weinstockj/gwassim#3]
The gates test is acting a bit weird sometimes. I ran the simulation below and got this from head(res):
  EFFECT_SIZE N_MARKERS N_BLOCKS        LD    sidaks   ccaTest     fisher vegas      gates
1           0        10       20 0.9486833 0.9332224 0.2143244 0.45046464 0.494 -0.7868429
2           0        10       20 0.9486833 0.5162588 0.2441303 0.86694181 0.680 -1.1917082
3           0        10       20 0.9486833 0.8298591 0.8204929 0.13615526 0.316 -0.9515823
4           0        10       20 0.9486833 0.7561221 0.5962192 0.04654634 0.231 -4.0177423
5           0        10       20 0.9486833 0.9825873 0.8785548 0.94366416 0.781 -1.1663027
6           0        10       20 0.9486833 0.9849406 0.7143334 0.97236963 0.784 -1.1383869

As you can see the gates p-values are not reasonable. I have tried to figure out what goes wrong sometimes, but I haven't yet been successful. Can you replicate this? Config code:

N_MARKERS = 10
LD = sqrt(.9)
N_COV = 1
sigma = matrix(LD, nrow = N_MARKERS, ncol = N_MARKERS)
diag(sigma) = 1
N_BLOCKS = 20
ALLELEFRQ = runif(N_MARKERS, .05, .95)
N_STRANDS = 2000
BLOCK_COR = .15
N_CAUSAL = 1
EFFECT_SIZE = .0
PHENO_DIST = "gaussian"
config = setConfiguration(N_MARKERS = N_MARKERS,
  LD = LD, sigma = sigma, N_COV = N_COV, ALLELEFRQ = ALLELEFRQ,
  N_STRANDS = N_STRANDS,
  N_BLOCKS = N_BLOCKS,
  BLOCK_COR = BLOCK_COR, N_CAUSAL = N_CAUSAL,
  PHENO_DIST = PHENO_DIST,
  EFFECT_SIZE = EFFECT_SIZE)

**Comment by weinstockj** [comment]
I can confirm this. Think I know where the bug is.

**Comment by weinstockj** [comment]
Found the bug. Multiplying by an eigenvalue in one extra place. Commit sent in and fixed. Just reinstall and it should work.
